### PR TITLE
Vendor boost lib

### PR DESCRIPTION
**Pull request by richfitz**
Copies the approach used in poppunk to remove the requirement for boost to be installed.

I'll come past later and try and get the whole thing pop installable, which will probably look a lot like the poppunk PR

### CODE REVIEW

**Review by johnlees — COMMENTED** [review]
Looks fine to me – if I still wanted to use the boost from conda when making the conda package would I be able to? Or would that require an update to the CMakeLists? (we usually set an environment variable in setup.py that will tell us whether this is the conda build or not)

**Comment by richfitz** [comment]
you'd need to change the CMakeLists, but it's not clear to me why you'd want to use the conda boost version?

**Comment by johnlees** [comment]
I suppose I was thinking if dynamic bitset ever gets updated to a new version it would be easier to pull in the update that way

**Comment by johnlees** [comment]
But I'm happy with this vendoring approach though – shall I merge?

**Comment by richfitz** [comment]
> I suppose I was thinking if dynamic bitset ever gets updated to a new version it would be easier to pull in the update that way

IMO this way is generally superior as you are in control of how that update happens, rather than it being on a subset of the users machines. You can update whenever you want, but it will be a change/commit to this repo.

Yes, fine to merge, but you might need to run that build-linux action yourself?

**Comment by johnlees** [comment]
I think I've got the action setup wrong, it doesn't run that final step on PRs... need to fix that at some point

**Review by johnlees — APPROVED** [review]

**Pull request merged**
